### ISSUE TITLE
Container div for report issue covers full width, preventing clicks

### ISSUE THREAD

**Issue by jasikpark** [bearcove/feedback#47]
I found something wrong on this page:

https://fasterthanli.me/articles/lies-we-tell-ourselves-to-keep-using-golang#position=37.3

Here's what it is:

The div you use to position the report issue button 👀 covers the entire page, so it prevents clicking on links that are covered by the invisible full-page-width div.

If you don't need additional buttons in the div maybe just style the anchor link itself and use [`width: fit-content`](https://developer.mozilla.org/en-US/docs/Web/CSS/fit-content)?

**Comment by jasikpark** [comment]
![image](https://user-images.githubusercontent.com/10626596/166341817-888b17e4-744d-4912-b34d-eb728d6f78a1.png)

**Comment by fasterthanlime** [comment]
@jasikpark the Feedback button is now in the sticky header. Is it usable for you now?

**Comment by jasikpark** [comment]
Yep, that seems functional 👍 

I looked into how to do your previous design.. it looks like you could get it modifying <https://www.digitalocean.com/community/tutorials/css-position-sticky>:

<img width="1482" alt="Screen Shot 2022-05-08 at 21 14 17" src="https://user-images.githubusercontent.com/10626596/167329255-058d0fa0-46aa-4ae9-a9c2-60c8f57807c9.png">


Setting:

```css

.content {
  display: flex;
  flex-direction: column;
}

and

.report-issue {
	position: sticky;
	width: fit-content;
	text-align: right;
	top: 10px;
	right: 10px;
	display: flex;
	flex-direction: row;
	justify-content: flex-end;
	z-index: 10;
	align-self: flex-end;
}
```

`flex-end` allows it to position itself on the right side of the screen w/o spanning the entire screen invisibly 😁 

It doesn't look like that messes with the rest of your paragraph flow? But I dunno 🤷
